[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
    NODE_VERSION = "20"
  
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
